version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: mysql:5.6
    restart: always
    volumes:
      - sqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
  app:
    image: one
    restart: always
    ports:
      - 81:80
    volumes:
      - userdata:/root
volumes:
  userdata:
  sqldata:


